### PR TITLE
Update tools.md

### PR DESCRIPTION
**Pull request by JonathanMagnan**
Added a "Tools" section for EF6 as seen for EF Core: https://learn.microsoft.com/en-us/ef/core/extensions/#extensions 
Added a "Extensions" section for EF6 as seen for EF Core: https://learn.microsoft.com/en-us/ef/core/extensions/#extensions Added multiple free & paid extensions under the newly added "Extensions" section

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/EntityFramework.Docs?pullRequest=4197) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/EntityFramework.Docs?pullRequest=4197) before we can accept your contribution.<br/><br/>:x: JonathanMagnan [sign now](https://cla.dotnetfoundation.org/dotnet/EntityFramework.Docs?pullRequest=4197)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/EntityFramework.Docs?pullRequest=4197) it.</sub>

**Comment by roji** [comment]
@JonathanMagnan we're generally no longer maintaining the EF6 docs, and merging a list of tools/extensions that references a single vendor/maintainer seems a bit problematic...

**Comment by roji** [comment]
We'll see what the other team members think, but I don't think we generally want to maintain a list of extensions/plugins for EF6, given that we're no longer actively maintaining it or its docs.

**Comment by ajcvickers** [comment]
This PR has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.

**Pull request closed without merging**
