### PR TITLE
Introduce bulk update and bulk delete in EF Core 7

### PR DESCRIPTION
**Pull request by yanxiaodi**
EF Core 7 enables bulk update/delete already. So it should be added to the documents.

### CODE REVIEW

**Comment by roji** [comment]
This is #4032. Note that I have partially written docs for this (which I haven't completed yet); we need to update more than just the perf page - also the "save data" section of the docs.

**Comment by yanxiaodi** [comment]
Thanks @roji I didn't notice that issue. Sure we can close this PR and wait for your update. Just think that users may not get the new features because of the outdated doc. Thanks!

**Comment by roji** [comment]
@yanxiaodi we do have pretty extensive documentation in the [7.0 What's New page](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#executeupdate-and-executedelete-bulk-updates), though it's true we also need to integrate this into our regular docs.

**Comment by yanxiaodi** [comment]
Agree @roji. When will complete the doc? Should we just add a link to [7.0 What's New page](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#executeupdate-and-executedelete-bulk-updates) to avoid any confusion? I can make changes on this PR. Thanks.

**Comment by ajcvickers** [comment]
Note from triage: we will wait for PR from @roji. Thanks anyway, @yanxiaodi!

**Pull request closed without merging**
