### PR TITLE
Fix Sqlite ToString example in 6.0 what's new

### LINKED ISSUE #3210: "Translate ToString on SQLite" example is wrong
in the docs the C# code should generate a List<User> but the code at
https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-6.0/whatsnew#translate-tostring-on-sqlite
claims that the generated SQL is "SELECT COUNT(*)", whereas I think it should generate "SELECT u.*"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 642054ea-366d-f8a2-4495-3e491b78fe1c
* Version Independent ID: e8884181-676d-4846-b2b7-ad0a3c7c1a3f
* Content: [What's New in EF Core 6.0](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-6.0/whatsnew)
* Content Source: [entity-framework/core/what-is-new/ef-core-6.0/whatsnew.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/what-is-new/ef-core-6.0/whatsnew.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

### PR DESCRIPTION
**Pull request by roji**
Fixes #3210

### CODE REVIEW

**Comment by ajcvickers** [comment]
@roji Have you run the code and verified that this change is correct?

**Comment by roji** [comment]
Apart from the ordering of the projection columns (which I just fixed), yeah, it seems right. Am I missing something?

<details>
<summary>C# code</summary>

```c#
await using var ctx = new BlogContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

_ = ctx.Users.Where(u => EF.Functions.Like(u.PhoneNumber.ToString(), "%555%")).ToList();

public class BlogContext : DbContext
{
    public DbSet<User> Users { get; set; }

    static ILoggerFactory ContextLoggerFactory
        => LoggerFactory.Create(b => b.AddConsole().AddFilter("", LogLevel.Information));

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlite("Filename=/tmp/test.sqlite")
            .EnableSensitiveDataLogging()
            .UseLoggerFactory(ContextLoggerFactory);
}

public class User
{
    public int Id { get; set; }
    public string Username { get; set; }
    public long PhoneNumber { get; set; }
}
```

</details>

<details>
<summary>SQL</summary>

```sql
      SELECT "u"."Id", "u"."PhoneNumber", "u"."Username"
      FROM "Users" AS "u"
      WHERE CAST("u"."PhoneNumber" AS TEXT) LIKE '%555%'
```

</details>

**Comment by ajcvickers** [comment]
@roji Just wanted to check that you actually ran the sample code and verified that this is the SQL that is generated, since I always copy-paste the generated SQL, I never guess. So this must have been a copy-paste error on my side, but that seems weird; where did I get the incorrect SQL?

**Comment by roji** [comment]
I'm guessing maybe a previous version had Count() in the LINQ, and it was later removed or something? I mean, looking at the LINQ and SQL in the current page, it's very clear they're out of sync...

**Review by ajcvickers — APPROVED** [review]

**Pull request merged**
