### PR TITLE
Update index.md

### LINKED ISSUE #3639: Behaivor changes link is broken
subj

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cbb86f3-378b-e83d-56c3-c0532192bd13
* Version Independent ID: c96b2fcb-8af0-f05b-e188-a6c59dd9f428
* Content: [Port from EF6 to EF Core - EF](https://docs.microsoft.com/en-us/ef/efcore-and-ef6/porting/)
* Content Source: [entity-framework/efcore-and-ef6/porting/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/efcore-and-ef6/porting/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @JeremyLikness
* Microsoft Alias: **avickers**

### PR DESCRIPTION
**Pull request by JeremyLikness**
Update links to correct paths. Fixes #3639.

### CODE REVIEW

**Review by roji — APPROVED** [review]
Looks OK but I think we prefer xref for internal links such as these (/cc @smitpatel)

**Comment by JeremyLikness** [comment]
Thanks @roji. Am interested in what @smitpatel says because [this documentation](https://docs.microsoft.com/contribute/how-to-write-links#xref-cross-reference-links) suggests XREF is for API documentation.

**Comment by smitpatel** [comment]
xref references pages using their ids. That helps with API mainly so it can reference links from other docset. For pages in same docset - using relative file.md, using relative link path and using xref all works the same. We as a team went to use xref because that causes least number of break whenever we rename something as long as the unique id given to page doesn't change. One of those case where we defer from official docs for ease of maintenance. I frown upon using relative file path as we don't get warning about them being broken in build.

**Comment by roji** [comment]
> I frown upon using relative file path as we don't get warning about them being broken in build.

Yeah, that part seems pretty important.

**Comment by JeremyLikness** [comment]
I will squash/merge and look at migrating to xref on future revisions.

**Pull request merged**
