### PR TITLE
Update commit-failures.md

### PR DESCRIPTION
**Pull request by ricardodsanchez**
Fixed typo

### CODE REVIEW

**Comment by roji** [comment]
It seems that both acknowledgment and acknowledgement are valid variants (e.g. [Merriam Webster](https://www.merriam-webster.com/thesaurus/acknowledgment)).

**Comment by ricardodsanchez** [comment]
@roji The English version is _acknowledgment_ while the other is British. Since the rest of the text uses the English version, shouldn't all be consistent?

**Comment by roji** [comment]
> The English version is acknowledgment while the other is British.

Do you mean American? :rofl:

I don't have any objection to making this change, but out of personal curiosity, can you point to a dictionary talking about this distinction as a dialect thing?

**Comment by ricardodsanchez** [comment]
Yes, I meant American English. Here are a couple of references:

https://grammarist.com/spelling/acknowledgment-acknowledgement/

https://preply.com/en/question/which-is-correct-spelling-acknowledgement-or-acknowledgment-69816

**Review by roji — APPROVED** [review]
Thanks.

Merging this, hopefully I don't get in trouble with @ajcvickers :fearful:

**Pull request merged**
