### PR TITLE
Fetch and Environment Variables COSMOS_ENDPOINT and COSMOS_ACCOUNTKEY…

### PR DESCRIPTION
**Pull request by siegfried01**
… in place of hard coded values. Also: tidy up (condense) source code.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/EntityFramework.Docs?pullRequest=3585) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/EntityFramework.Docs?pullRequest=3585) before we can accept your contribution.<br/><br/>:x: siegfried01 [sign now](https://cla.dotnetfoundation.org/dotnet/EntityFramework.Docs?pullRequest=3585)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/EntityFramework.Docs?pullRequest=3585) it.</sub>

**Comment by siegfried01** [comment]
Approved

**Comment by ajcvickers** [comment]
@siegfried01 Can you explain a bit more why this is a good thing to do?

**Comment by siegfried01** [comment]
I'm trying to find a way to abort this pull request on github... I don't see an abort button. I thought I was doing a pull request on my  own fork. Can you guide me own aborting this pull request?

However: I would request that you read your ACCOUNTKEYS and URLS from environment variables so we don't have to search and replace through-out many occurrences in the source code.

Also: please use more helpful names than Program.cs all the time.

**Comment by ajcvickers** [comment]
@siegfried01 You just need to close it.

**Pull request closed without merging**
