### PR TITLE
Make breadcrumbs consistent with .NET and ASP.NET docs

### PR DESCRIPTION
**Pull request by scottaddie**
Fixes https://github.com/dotnet/EntityFramework.Docs/issues/2131

[Internal review page](https://review.docs.microsoft.com/ef/core/?branch=pr-en-us-2159)

This PR also updates the master ToC by:

- Removing gerunds, where it makes sense
- Convert titles to sentence case

### CODE REVIEW

**Comment by scottaddie** [comment]
@smitpatel @ajcvickers I have a bit more testing to do, but so far everything looks good. Hold off on merging for now.

**Comment by scottaddie** [comment]
@smitpatel @ajcvickers Ready for one last review. You can use the following link to preview the changes:

https://review.docs.microsoft.com/ef/core/?branch=pr-en-us-2159

**Comment by smitpatel** [comment]
A related weird thing. @ajcvickers can define behavior

https://review.docs.microsoft.com/en-us/ef/core/miscellaneous/testing/sqlite?branch=pr-en-us-2159
When clicking on fundamentals in breadcrumbs, it takes to connection strings page since there is no overview page for fundamentals. Should we make this experience somewhat better? How?

**Comment by scottaddie** [comment]
@smitpatel The preferred approach is to create an Overview page within the Fundamentals node. That doesn't exist, so I have it link to the Connection Strings doc instead.

**Comment by ajcvickers** [comment]
I think it's fine for now. But we should create an Overview page at some point. Filed #2160

**Pull request merged**
