### PR TITLE
Replace bold with headings in breaking changes pages

### PR DESCRIPTION
**Pull request by roji**
Keep the linter happy at all costs

### CODE REVIEW

**Comment by roji** [comment]
Also reduced heading level to make the breaking changes appear in the right-hand contents pane, do we like?

**Comment by AndriySvyryd** [comment]
The right-hand pane is pretty much unusable with this

**Comment by roji** [comment]
I thought it was useful to have the list, but can info they part of it seems bad.

**Comment by AndriySvyryd** [comment]
Perhaps just group them by impact?

**Comment by roji** [comment]
I'll give it a go.

**Comment by roji** [comment]
Done, looks pretty nice IMHO

**Review by AndriySvyryd — APPROVED** [review]

**Pull request merged**
