### PR TITLE
doc: add limitations

### PR DESCRIPTION
**Pull request by shahabganji**
Describe the limitation of Shadow Properties in the very first paragraph

### CODE REVIEW

**Comment by ajcvickers** [comment]
@shahabganji This change seems somewhat confusing to me since it implies that the CLR type has properties but they are not being set. Can you explain a bit more what limitation you are trying to convey?

**Comment by shahabganji** [comment]
@ajcvickers , I wanted to convey the difference between the following two queries: 

1. **With** `AsNoTracking()`

```cs 
 var authors = context.Authors.Select(x => x).AsNoTracking();

foreach (var author in authors)
{
    Console.WriteLine(
        $"The entity for AuthorId: {author.Id} " +
        $"was created at: {context.Entry(author).Property("CreatedOn").CurrentValue}");
}
```

2. **Without** `AsNoTracking()`
```cs
var authors2 = context.Authors.Select(x => x);
foreach (var author2 in authors2)
{
    Console.WriteLine(
        $"The entity for AuthorId: {author2.Id} " +
        $"was created at: {context.Entry(author2).Property("CreatedOn").CurrentValue}");
}
```

And the output will respectively be :


```bash
The entity for AuthorId: a2ab54b2-c72c-4644-8bf4-4fa48d3ee89d was created at: 01/01/0001 00:00:00 +00:00
```

```bash
The entity for AuthorId: a2ab54b2-c72c-4644-8bf4-4fa48d3ee89d was created at: 06/27/2020 16:31:47 +00:00
```
 And for clarity, the `CreatedOn` is a Shadow Property and the `Author` class is like this: 

```cs
public class Author
{
     public Guid Id { get; private set; }
     public string FirstName { get; private set; }
     public string LastName { get; private set; }
     public DateTime DateOfBirth { get; private set; }
}
```

**Comment by shahabganji** [comment]
I could also add a section with an example if you think that will provide a better understanding of the problem

**Comment by ajcvickers** [comment]
@shahabganji May add a sentence to `Accessing shadow properties`. Something like, "Shadow properties cannot be accessed after a no-tracking query since the entities returned are not tracked by the change tracker."

**Comment by shahabganji** [comment]
@ajcvickers, The changes applied.

**Comment by ajcvickers** [comment]
Thanks!

**Pull request merged**
