### PR TITLE
Update xamarin.md

### PR DESCRIPTION
**Pull request by Orin-Thomas**
ms.date freshness update

### CODE REVIEW

**Comment by Orin-Thomas** [comment]
#sign-off

**Comment by ajcvickers** [comment]
@Orin-Thomas Why is the date being changed here? Has the document itself been updated?

**Comment by Orin-Thomas** [comment]
@ajcvickers No changes - Just freshness review as the document was marked as "stale".

**Comment by ajcvickers** [comment]
@Orin-Thomas Has nothing changed since 2020? In other words, isn't this stale?

**Comment by Orin-Thomas** [comment]
@ajcvickers In the documentation / training sense it just means "has this been looked at and is it valid?". For example, most Active Directory stuff from 2016 hasn't needed alteration, but we review it and update its ms.date to say "yes this is still valid". Do you believe that the document needs to be removed and archived?

**Comment by ajcvickers** [comment]
I would be very surprised if docs written for Xamarin several years ago are still valid today. Have you tried working through the content?

**Comment by ErikEJ** [comment]
@Orin-Thomas F.ex. VS for Mac no longer exists

**Comment by Orin-Thomas** [comment]
I'll work on getting the doc archived!

**Comment by Orin-Thomas** [comment]
Shifting to archive of doc

**Pull request closed without merging**
