### PR TITLE
Updated EF Core Power Tools CLI link

### PR DESCRIPTION
**Pull request by snaits**
The original link to the EF Core Power Tools CLI was broken. 

I have updated it with a link to the most recent (EF7) readme

### CODE REVIEW

**Comment by ErikEJ** [comment]
It is probably better to.link to the readme tab on Nuget.org

**Comment by snaits** [comment]
Good point - this one? 
https://www.nuget.org/packages/ErikEJ.EFCorePowerTools.Cli/#readme-body-tab

**Comment by ErikEJ** [comment]
Should change "GitHub readme" to "NuGet" ...

**Comment by ErikEJ** [comment]
LGTM - thanks!

**Review by roji — APPROVED** [review]
Thanks!

**Pull request merged**
