### PR TITLE
Add Reconciler to list of extensions

### PR DESCRIPTION
**Pull request by jtheisen**
Reconciler is an extension that allows to update an entity graph to match a given one.

This was already once part of this page, but I asked to remove it several years ago as it was too buggy. I recently had a good overhaul and extended the test suite significantly. I think it's now ready to be listed again.

### CODE REVIEW

**Comment by ErikEJ** [comment]
Please specify the supported EF Core versions like it is done for all other extensions.

**Comment by jtheisen** [comment]
Done

**Comment by ErikEJ** [comment]
I cannot see that the package supports EF Core 3, looks more like EF Core 6 (and maybe 7 and 8)

**Comment by jtheisen** [comment]
Fixed the pull request to only state support for 6 and 7. It used to support 3.1 and I forgot that I updated the version reference at some point - I'll have a look later if I can still support earlier versions.

**Comment by ErikEJ** [comment]
LGTM!

**Review by ajcvickers — APPROVED** [review]

**Comment by ajcvickers** [comment]
Thanks @jtheisen, and thanks @ErikEJ for reviewing these as always. :-)

**Pull request merged**
