### PR TITLE
Filter out API members with [EntityFrameworkInternal]

### LINKED ISSUE #3029: Exclude APIs members marked with [EntityFrameworkCoreInternal]
Public docfx allows [filtering out APIs marked with a specific attribute](https://dotnet.github.io/docfx/tutorial/howto_filter_out_unwanted_apis_attributes.html#3-exclude-or-include-apis-by-containing-matched-attributes). We can do this to keep out members annotated with [EntityFrameworkCoreInternal].

### PR DESCRIPTION
**Pull request by roji**
Closes #3029

@smitpatel any way to validate/test this?

### CODE REVIEW

**Comment by roji** [comment]
Also:

image

**Comment by roji** [comment]
Doesn't seem to work, though I'm seeing examples of this for public docfx...

**Comment by smitpatel** [comment]
This is incorrect repository.

**Comment by roji** [comment]
Ah, OK - though note that there is a metadata section in the docfx referencing sources, maybe that should be cleaned up.

In any case, do you know where this should go?

**Comment by smitpatel** [comment]
Since there is no src in this repo, that section is actually no-op.
Is this build time filtering or render time? i.e. Does this filtering apply to ECMAXML or the generation of it?

**Comment by roji** [comment]
> Since there is no src in this repo, that section is actually no-op.

Yeah, I can change this PR to simply remove it.

>  Is this build time filtering or render time? i.e. Does this filtering apply to ECMAXML or the generation of it?

image

**Comment by smitpatel** [comment]
Can you link me to the doc of filtering in public docfx build? I will ask the team which is generating our API docs for us.

**Comment by roji** [comment]
Here you go: https://dotnet.github.io/docfx/tutorial/howto_filter_out_unwanted_apis_attributes.html#3-exclude-or-include-apis-by-containing-matched-attributes

**Comment by roji** [comment]
@smitpatel if you're looking at this with the docs people, you may want to also mention that the Microsoft.EntityFrameworkCore.Metadata.Builders.Internal namespace does seem to show up in our API docs, though Internals are supposed to be filtered out...

(thanks for managing this stuff!)

**Comment by smitpatel** [comment]
We manage the filtering. I updated our filters. Website should be updated in some time.

**Comment by roji** [comment]
@smitpatel thanks, closing this. #3029 tracks filtering out the attribute as well.

**Pull request closed without merging**
