### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by JulieDevMagic**
Added a new EF Core extension for EF Core developers to try.

### CODE REVIEW

**Comment by JulieDevMagic** [comment]
#sign-off

**Comment by ErikEJ** [comment]
Maybe move below EF Core Power Tools CLI?

**Comment by JulieDevMagic** [comment]
> Maybe move below EF Core Power Tools CLI?

Ok

**Comment by ErikEJ** [comment]
LGTM!

**Comment by roji** [comment]
Sorry, but could you please move your tool down below LLBLGen and Devart as well? These are mature tools that have been around for a very long time.

**Comment by JulieDevMagic** [comment]
> Sorry, but could you please move your tool down below LLBLGen and Devart as well? These are mature tools that have been around for a very long time.

Sorry.  OK.

**Comment by JulieDevMagic** [comment]
#sign-off

**Comment by JulieDevMagic** [comment]
#sign-off

**Comment by JulieDevMagic** [comment]
#sign-off

**Review by ajcvickers — APPROVED** [review]

**Comment by ajcvickers** [comment]
Thanks!

**Pull request merged**
