### PR TITLE
Explanation correction of dependent navigation unavailability

### PR DESCRIPTION
**Pull request by darul9061**
correction on the statement for adding shadow foreign when the dependent navigation is not available

### CODE REVIEW

**Comment by ajcvickers** [comment]
@darul9061 Is there a reason this is a draft PR? Are you intending to continue with it?

**Comment by darul9061** [comment]
@ajcvickers I had to leave it as a draft pr because I didn't have the permission to make a merge request. Thanks

**Comment by ajcvickers** [comment]
@darul9061 What do you mean by, "I didn't have the permission?"

**Comment by darul9061** [comment]
@ajcvickers I had the access denial error or some sort after requesting a pull request.

**Comment by ajcvickers** [comment]
Closing as the PR is not moving out of draft. We can re-open if it becomes a PR we can review.

**Pull request closed without merging**
