### PR TITLE
Initial update to run samples on .NET 6 with EF Core 6.0

### PR DESCRIPTION
**Pull request by ajcvickers**
Part of #3023

### CODE REVIEW

**Comment by roji** [comment]
Shouldn't we just wait for the actual 6.0.0 GA?

**Comment by ajcvickers** [comment]
@roji Wanted to find issues like https://github.com/dotnet/efcore/issues/26542 ASAP.

**Comment by ajcvickers** [comment]
We could delay merging, I guess.

**Comment by roji** [comment]
With the release so close, might as well, it seems...

**Comment by ajcvickers** [comment]
@dotnet/efteam Updated all versions to 6.0.0.

**Review by roji — APPROVED** [review]

**Pull request merged**
