### PR TITLE
ROPC: connections strs and includes

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Contributes to #4788

[INternal review URL](https://review.learn.microsoft.com/en-us/ef/core/miscellaneous/connection-strings?branch=pr-en-us-4842)

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@wadepickett @tdykstra  do you know how to fix the lint error - lint is not recognizing an include file

**_Error: entity-framework/core/includes/managed-identities-test-non-production.md:8 MD041/first-line-heading/first-line-h1 First line in a file should be a top-level heading [Context: "> [!WARNING]"]_**

**Comment by tdykstra** [comment]
> @wadepickett @tdykstra do you know how to fix the lint error - lint is not recognizing an include file
> 
> **_Error: entity-framework/core/includes/managed-identities-test-non-production.md:8 MD041/first-line-heading/first-line-h1 First line in a file should be a top-level heading [Context: "> [!WARNING]"]_**

Suggestion of something worth trying: There isn't an includes folder yet; ignore the warning and merge the PR and then subsequent PRs should be OK.

**Comment by tdykstra** [comment]
> > @wadepickett @tdykstra do you know how to fix the lint error - lint is not recognizing an include file
> > **_Error: entity-framework/core/includes/managed-identities-test-non-production.md:8 MD041/first-line-heading/first-line-h1 First line in a file should be a top-level heading [Context: "> [!WARNING]"]_**
> 
> Suggestion of something worth trying: There isn't an includes folder yet; ignore the warning and merge the PR and then subsequent PRs should be OK.

Hold off on that, I bet there's some markdownlint configuration that says ignore includes folders, I'm going to check that out...

**Comment by Rick-Anderson** [comment]
That got rid of the 1st markdown lint error(push), but not the second (pull_request)
that's OK, we can live with that..

**Review by AndriySvyryd — APPROVED** [review]

**Pull request merged**
