### PR TITLE
.NET Core 2.1 does not support .NET Standard 2.1

### PR DESCRIPTION
**Pull request by teo-tsirpanis**
The "Breaking changes in EF Core 5.0" was stating otherwise and was updated.

### CODE REVIEW

**Review by AndriySvyryd — APPROVED** [review]

**Comment by AndriySvyryd** [comment]
Thanks for your contribution!

**Comment by ajcvickers** [comment]
@AndriySvyryd .NET Core 2.1 does support .NET Standard 2.1. What am I missing here?

**Comment by teo-tsirpanis** [comment]
@ajcvickers

image

**Comment by ajcvickers** [comment]
@teo-tsirpanis Thanks. My mistake.

**Pull request merged**
