### PR TITLE
3203-add multiple parameter examples for FromSqlRaw

### LINKED ISSUE #3203: Multiple parameter examples for FromSqlRaw and related
You should have examples also with multiple parameters FromSqlRaw...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e1289d5-8364-18a4-3445-6bba05c6854b
* Version Independent ID: 2680e647-f64a-7991-f821-3b5e2a845960
* Content: [Raw SQL Queries - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/raw-sql#passing-parameters)
* Content Source: [entity-framework/core/querying/raw-sql.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/querying/raw-sql.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @smitpatel
* Microsoft Alias: **avickers**

### PR DESCRIPTION
**Pull request by Rezakazemi890**
- [x] I've read the guidelines for [contributing](CONTRIBUTING.md) and seen the [walkthrough](https://youtu.be/9OMxy1wal1s?t=1869)
- [x] I've posted a comment on an issue with a detailed description of how I am planning to contribute and got approval from a member of the team
- [x] The code builds and tests pass locally (also verified by our automated build checks)
- [x] Commit messages follow this format:
```
        Summary of the changes
        - add multiple parameter examples for FromSqlRaw.
        
        Fixes #3203
```
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Code follows the same patterns and style as existing code in this repo

Fixes #3203

### CODE REVIEW

**Comment by ajcvickers** [comment]
@Rezakazemi890 The code no longer aligns with the text that surrounds it.

Note for team: I'm not sure what value there is in showing multiple parameters.

**Comment by Rezakazemi890** [comment]
> @Rezakazemi890 The code no longer aligns with the text that surrounds it.
> 
> Note for team: I'm not sure what value there is in showing multiple parameters.

@ajcvickers 
Do you mean this part of the text?
https://learn.microsoft.com/en-us/ef/core/querying/sql-queries#passing-parameters:~:text=In%20the%20above,rejecting%20such%20inputs.

And that it should be changed according to the code?
If you approve, I will change that part of the text as well.

**Comment by roji** [comment]
> I'm not sure what value there is in showing multiple parameters

@ajcvickers I agree - I don't see what value this adds... Better keep the samples simple and minimal.

**Comment by ajcvickers** [comment]
Closing based on discussion above.

**Pull request closed without merging**
