### PR TITLE
Fix Grammar

### PR DESCRIPTION
**Pull request by erhanalankus**
Although stored computed columns seem like a good solution => Although using stored computed columns seems like a good solution

### CODE REVIEW

**Review by roji — COMMENTED** [review]
How is the proposed text more grammatical than the existing one?

**Comment by erhanalankus** [comment]
The existing one seems incorrect to me.
If it's talking about plural things, the sentence should go like "seem like good solutions".
It's talking about using stored columns. So it should go like "seems like a good solution.

**Comment by roji** [comment]
I don't think it's incorrect to refer to a plural as a singular, e.g. "apples are a nice fruit", "these apartments seem like a good investment".

**Comment by ajcvickers** [comment]
Note from triage: we decided not to take this. Thanks anyway!

**Pull request closed without merging**
