### PR TITLE
AfterSaveBehavior default is actually .Ignore, not .Throw

### PR DESCRIPTION
**Pull request by dbrownems**
Updating docs to match actual behavior of `AfterSaveBehavior`, and to clarify treatment of database-side changes in case of .Save and .Ignore

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@dbrownems  can you check my changes? Avoid future tense and split up long sentences.

**Comment by ajcvickers** [comment]
@Rick-Anderson The reason this isn't merged is that I still need to investigate the technical aspects of this.

**Comment by smitpatel** [comment]
@ajcvickers - Also include changes from #2372 depending on the decision.

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/EntityFramework.Docs?pullRequest=2371) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/EntityFramework.Docs?pullRequest=2371) before we can accept your contribution.<br/><br/>:x: dbrownems [sign now](https://cla.dotnetfoundation.org/dotnet/EntityFramework.Docs?pullRequest=2371)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/EntityFramework.Docs?pullRequest=2371) it.</sub>

**Comment by Rick-Anderson** [comment]
> @ajcvickers - Also include changes from #2372 depending on the decision.

@smitpatel  I added it.

**Comment by Rick-Anderson** [comment]
@dbrownems  thanks for the review. When I added your other commit to this PR it pushed you over the limit to require a signed CLA to accept the PR. Would you mind signing that?

[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/EntityFramework.Docs?pullRequest=2371) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/EntityFramework.Docs?pullRequest=2371) before we can accept your contribution.<br/><br/>:x: dbrownems [sign now](https://cla.dotnetfoundation.org/dotnet/EntityFramework.Docs?pullRequest=2371)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/EntityFramework.Docs?pullRequest=2371) it.</sub>

**Comment by ajcvickers** [comment]
@roji Is this obsolete now that you updated these pages?

**Comment by roji** [comment]
Yeah, this has been corrected in #2998 - one needs to do `SetAfterSaveBehavior(PropertySaveBehavior.Save)` in order to provide explicit values for properties configured as OnAddOrUpdate. [The default is Ignore for OnUpdate properties](https://github.com/dotnet/efcore/blob/0b31650/src/EFCore/Extensions/PropertyExtensions.cs#L286), which makes explicit values ignored, whereas Save makes them properly sent to the database. I've just tested this again and it works this way.

* I'm new to this area, but I wonder - is there any reason for Ignore to be the default for on-update-generated properties? Doesn't this just make them non-overridable by default, is there any reason not to return Save here instead?
* FWIW the XML docs on [SetAfterSaveBehavior](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.mutablepropertyextensions.setaftersavebehavior?view=efcore-5.0#Microsoft_EntityFrameworkCore_MutablePropertyExtensions_SetAfterSaveBehavior_Microsoft_EntityFrameworkCore_Metadata_IMutableProperty_System_Nullable_Microsoft_EntityFrameworkCore_Metadata_PropertySaveBehavior__) seem unclear on all this - they discuss what happens "whether this property can be modified after the entity is saved to the database", but at least in this case it's more about whether the user-set value is sent to the database or not.
* Opened #23912 for what seems to be a bug when using explicit values when *adding* the entity.

**Pull request closed without merging**
