### PR TITLE
Top-level statements for EFGetStarted

### PR DESCRIPTION
**Pull request by danielniccoli**
Migrate EFGetStarted sample to using top-level statements feature. (https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/program-structure/top-level-statements)

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/EntityFramework.Docs?pullRequest=3865) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/EntityFramework.Docs?pullRequest=3865) before we can accept your contribution.<br/><br/>:x: danielniccoli [sign now](https://cla.dotnetfoundation.org/dotnet/EntityFramework.Docs?pullRequest=3865)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/EntityFramework.Docs?pullRequest=3865) it.</sub>

**Comment by roji** [comment]
Briefly discussed in #2697. Not sure if we decided something specifically for the getting started sample, top-level statements may have been too new (and therefore unfamiliar to new users).

**Comment by danielniccoli** [comment]
Not sure where to discuss this, as the ticket you mention is closed. So I'll briefly give my opinion here. Maybe you have a suggestion where to put this. 

> Top-level statements may have been too new (and therefore unfamiliar to new users).

 - Top-level statements are is enabled for new project by default, since November 2020.
 - People new to C# will probably start with the official [Hello World](https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/tutorials/hello-world) tutorial, which also uses top-level statements.

So if anyone is unfamiliar with top-level statements, it's old users, not new users. 🙂

Top-level statements are going to stay. They have been the recommended way to start new C# projects since November 2020 and will be in the future.

Creating a new .NET console project will create a top-level statement based sample code. Consequently, when following the "Getting Started" tutorial for EF, running `dotnet new console -o EFGetStarted`, you already start with top-level statements.

When you create a ASP.NET Core 6 Web App, a Razor App, or a Blazor App, you start with a top-level statement sample. The official tutorial for ASP.NET Core 6 uses top-level statements e.g., the one for [Razor Pages](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-6.0&viewFallbackFrom=aspnetcore-2.1&tabs=visual-studio)

It makes no sense that the EF Get Started tutorial keeps using `void Main()`, while everything else uses top-level statements.

**Comment by roji** [comment]
@danielniccoli I don't disagree with you, but the team had other thoughts. It's a while later, so we'll revisit this when triaging this issue.

**Comment by roji** [comment]
Actually I forgot we've already received #3828 for this, and decided it was OK to do it. I'll look at both PRs soon and merge one.

**Review by roji — APPROVED** [review]

**Pull request merged**
