### PR TITLE
DocuTune: Apply metadata properties for advocate contributors

### PR DESCRIPTION
**Pull request by alexbuckgit**
DocuTune: Apply metadata properties for advocate contributors

Note the following:

- DocuTune drives improved quality of technical content by finding and automatically correcting a broad set of issues in Markdown and YAML files. DocuTune performs these updates intelligently, only making corrections in the sections of a document where the correction is suitable.
- DocuTune PRs often standardize spacing, formatting, and casing of Markdown elements to support the DocuTune onboarding process.
- DocuTune PRs might contain other minor edits noticed during a manual review.
- DocuTune PRs might include files whose Acrolinx score was below the target threshold prior to this PR.
- Delimiters such as asterisks and backticks may be added to link descriptions or alt-text to denote UI elements or other string literals that should not be modified during automation.
- Other formatting or indentation corrections might appear in DocuTune PRs to improve the accuracy of document parsing.

PointOfContact: @scottboc (Scott Bockheim)
CorrelationId: 70d29a1f-52c7-4693-b6b6-48364523765f

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
Recommend closing this. @scottboc do you know about this.  @alexbuckgit has opened many of similar PR's and he doesn't respond to what this is for.

**Comment by ajcvickers** [comment]
Closing based on @Rick-Anderson's suggestion.

**Comment by Rick-Anderson** [comment]
Reached out to  @scottboc  and  @alexbuckgit, both MS employees and this is legitimate. Sorry for the false alarm.

**Comment by Rick-Anderson** [comment]
. DocuTune is an automated content remediation tool used by Content Governance & Excellence to apply content and metadata improvements in support of business initiatives like the one Scott described. 
As we work to further operationalize and run these kinds of updates at scale, we'll ensure the workflow surfaces PR comments to be addressed during the workflow.

**Comment by mikekinsman** [comment]
@Rick-Anderson we'd like to get this merged before the next monthly data pull.  Is there anything we can do to get this merged before 4/1?  Thanks!  cc @alexbuckgit

**Comment by smitpatel** [comment]
@Rick-Anderson & others, can you reach out to me via email regarding details of this? How this work? What effect it causes on the docs itself? What is guidelines in terms of how and when to use this on docs pages?

**Comment by Rick-Anderson** [comment]
> What effect it causes on the docs itself? What is guidelines in terms of how and when to use this on docs pages?

0 impact on docs from an external point of view. It's just for internal accounting.

@alexbuckgit  can respond internally.

**Comment by JeremyLikness** [comment]
@alexbuckgit I think if you can remove wpf from the PR we are good to merge.

**Pull request closed without merging**
