### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by OOberoi**
Just a handful of missing punctuation marks.

### CODE REVIEW

**Review by roji — COMMENTED** [review]
This doesn't seem like idiomatic English to me ([see e.g. this](https://jakubmarian.com/comma-before-that-and-which/)) - in any case it's not the style we've used in our docs so far.

**Comment by OOberoi** [comment]
Sounds good!

Thanks,

Obi Oberoi – (M.Sc.)
Cell: (647) 298 7130

**Comment by smitpatel** [comment]
I ran through the tool and tool suggest that comma shouldn't be used (along with the fact that this should not be used without noun too). Closing this PR as the change doesn't align with doc writing guidelines.

**Comment by OOberoi** [comment]
Thanks for the input!

**Pull request closed without merging**
