### PR TITLE
Wrong code sample for AsSplitQuery/AsSingleQuery

### PR DESCRIPTION
**Pull request by joakimriedel**
Note - this is just raw edited in Github, have not verified locally that this will build and that the link will actually work. Hence draft pull request.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/EntityFramework.Docs?pullRequest=2659) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/EntityFramework.Docs?pullRequest=2659) before we can accept your contribution.<br/><br/>:x: joakimriedel [sign now](https://cla.dotnetfoundation.org/dotnet/EntityFramework.Docs?pullRequest=2659)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/EntityFramework.Docs?pullRequest=2659) it.</sub>

**Comment by joakimriedel** [comment]
ping @roji how do I proceed with this? first time pull request, but found a small typo in the docs.

**Comment by joakimriedel** [comment]
Found out how to test locally, this is ready for review.

**Review by roji — APPROVED** [review]
Thanks for catching this!

**Pull request merged**
