### PR TITLE
Missing update-database

### PR DESCRIPTION
**Pull request by oskarj**
There should be an update-database after applying a blank merge before "continue developing"

### CODE REVIEW

**Comment by ajcvickers** [comment]
@oskarj What errors do you see if you don't do this step?

**Comment by oskarj** [comment]
@ajcvickers the context is out of sync, if you have a Database initializer that checks if the model has changed when the application is starting you will get an exception with the message "the model backing context has changed" so you need to run update-database in order to get that migration into __MigrationHistory table.

**Comment by ajcvickers** [comment]
Thanks @oskarj!

**Pull request merged**
