### PR TITLE
Update Azure Cosmos DB EF docs

### PR DESCRIPTION
**Pull request by jcocchi**

### CODE REVIEW

**Comment by jcocchi** [comment]
@dotnet-policy-service agree company="Microsoft"

**Comment by SamMonoRT** [comment]
Adding @jamesmontemagno as reviewer till we clarify the ownership rights on the repo.  
@jcocchi  - the changes look good, I'll approve, but please wait for an additional approval.

**Comment by SamMonoRT** [comment]
cc @cmastr

**Review by jamesmontemagno — APPROVED** [review]

**Comment by jamesmontemagno** [comment]
Perhaps @IEvangelist can help out here

**Review by roji — APPROVED** [review]
Thanks @jcocchi these are all great suggestions.

@SamMonoRT am OK for this to be merged but will let you do it in case you want any further reviewing/etc. Once it's merged I'll push it live.

**Pull request merged**
