### PR TITLE
Update existing-database.md

### PR DESCRIPTION
**Pull request by thiggins1990**
fixed a typo

### CODE REVIEW

**Review by roji — APPROVED** [review]
Thanks!

**Comment by roji** [comment]
@ajcvickers can you please force-merge this as admin?

**Comment by ajcvickers** [comment]
@smitpatel Any idea why `lint` is hanging?

**Comment by roji** [comment]
Github Actions had some issues recently - I was affected on Npgsql too. I'm not sure if there's a way to retrigger that lint workflow...

**Comment by ajcvickers** [comment]
It re-triggeed when I closed and re-opened the PR, but it's still hanging in the same way.

**Comment by smitpatel** [comment]
Can we make lint non-required check instead?

**Comment by ajcvickers** [comment]
I don't have permissions to change these things in docs.

**Comment by smitpatel** [comment]
@thiggins1990 - Thank you for the contribution.

**Pull request merged**
