### PR TITLE
(AzureCXP) Correct description

### PR DESCRIPTION
**Pull request by BhargaviAnnadevara-MSFT**
The doc probably means ".. EF6 to EF Core" instead of ".. EF6 to .NET Core"

### CODE REVIEW

**Comment by roji** [comment]
Thanks!

**Comment by smitpatel** [comment]
This is incorrect change. Need to revert!

**Comment by roji** [comment]
Sorry, read through too quickly - reverted. The last bit of the page is somewhat confusing between EF Core and .NET Core.

**Comment by ajcvickers** [comment]
@roji Can elaborate on what's confusing? I read it again and it seems clear to me! :-)

**Comment by roji** [comment]
Just that the whole document deals with EF Core vs. EF6, and even the title of that last section doesn't actually say it's discussing guidance for potentially moving to .NET Core (just "Guidance for existing EF6 applications"). It may be worth putting that content in a top-level section explicitly entitled ".NET Framework and .NET Core" or similar.

It's not big deal - but both I and @BhargaviAnnadevara-MSFT misunderstood on a quick reading.

**Pull request merged**
