### PR TITLE
Update relationships.md

### PR DESCRIPTION
**Pull request by NielsPilgaard**
Hi 👋 
I noticed this word was missing when reading the docs, so I thought I'd add it.

### CODE REVIEW

**Review by roji — APPROVED** [review]
Thanks!

**Comment by roji** [comment]
@NielsPilgaard can you please accept the CLA by commenting "@dotnet-policy-service agree"?

**Comment by NielsPilgaard** [comment]
@dotnet-policy-service agree

**Comment by ajcvickers** [comment]
Thanks!

**Comment by NielsPilgaard** [comment]
Sure thing!

**Pull request merged**
